### PR TITLE
Pre-release changes for v0.1.0

### PR DESCRIPTION
**Pull request by vgeorge**
This PR will add a landing page for unlogged users, see #10. I've moved the login flow to start from the landing page. When the user is logged in, it should be redirected to `/traces`. When it signs out, it is redirect to `/`.

@LanesGood I thought the background would be a single image, but I saw now it is a composite. I believe you would do a better job including and positioning the pieces, please let me if you need help.

### CODE REVIEW

**Comment by LanesGood** [comment]
@vgeorge this wont let me request a review from you, but I've done the majority of the styles for the landing page.

Do you have any suggested sources for higher res satellite images that are already processed? This background image is from a mapbox Sketch plugin that maxes out at 1200px width. I think it looks blurry here.

There is also something weird happening with the grid width and scrolling at small screen sizes; I could keep exploring this as needed or just ignore for now, as we don't have any responsiveness built into the rest of the app.

image

**Comment by vgeorge** [comment]
@LanesGood this is looking good on Firefox, but on Chrome the mobile screens are misaligned:

Screenshot 2019-12-11 13 39 49

Regarding the image, Ricardo suggested this link:

https://earthobservatory.nasa.gov/images

You can download the image with enough resolution by browsing to the page and clicking on JPEG:

Screenshot 2019-12-11 13 42 27

I added commits to solve the remaining issues before releasing [v0.1.0](https://github.com/developmentseed/observe-dashboard/milestone/1):

- #42: I didn't remove the id as I thought that they could be useful, but moved the date first
- #28: All pages, index and views, are now displaying dates in UTC, formatted to browser's locale
- #29: rounded at index page, but left the full on view page to have the database value displayed on the dashboard
- #43: When photos/traces don't exist, the user is redirect to the index and a toast is displayed

@geohacker @batpad @sethvincent this should be the last PR before the release, it would be good if you could review too.

**Comment by vgeorge** [comment]
You should use the API from https://github.com/developmentseed/observe-api/pull/48.

**Comment by vgeorge** [comment]
@LanesGood as we discussed, I moved the id back to the first column. Added "UTC" to traces/photos page, and fixed a bug on the delete icon that was enabled for non-admin users. Please review again.

**Pull request merged**
