### PR TITLE
Allow setting application pathname

### PR DESCRIPTION
**Pull request by vgeorge**
This PR updates links and configuration options to allow deploying the app to a non-root pathname. See #47. Changes:

- Updated all assets and internal links to be relative to application pathname
- Add `appPathname` option to config

@sethvincent I believe we can't test this in surge, because we need a way to redirect 404s back to index.html, which is not possible on non-root pathnames on that service. The production env must have a nginx rule or similar redirecting any `/observe/*` 404 to `/observe/index.html`. I already set 
`appPathname` to `/observe`. If you need to change this, you can add a `app/assets/scripts/config/local.js` with instance specifc options. Please review.

### CODE REVIEW

**Comment by sethvincent** [comment]
Ah, that makes sense about surge.

Thank you for this, I'll test it out.

**Comment by sethvincent** [comment]
@vitor I added a commit that's needed for router links to respect the base pathname and that also improves the index.html changes to work both when there's a trailing slash and when there isn't. Incidentally this included making use of the `<base>` tag. This looks to be working well on staging.

**Comment by vgeorge** [comment]
@sethvincent, added a commit to make <base> change depend on environment and rolled back changes in internal links (thanks to @danielfdsilva). Please check if it still works. It would be good to confirm if you can enter in a trace page and go back by clicking on "< Back to Traces":

observe

**Comment by vgeorge** [comment]
I meant "added a commit to make `<base>` tag change on environment". It was hard coded on index.html.

**Comment by sethvincent** [comment]
@vgeorge I'm seeing a [login error from the api](https://github.com/developmentseed/observe-api/issues/45) so I haven't been able to test the back to traces button, but everything that I can click on is working well.

**Comment by vgeorge** [comment]
@sethvincent, I did a rebase of this. can you please review if it works with the latest API changes?

**Comment by sethvincent** [comment]
@vgeorge I did some debugging on staging and run into a couple small issues where `appPathname` wasn't in use where it should be. I added commits to fix those things. This looks good to me.

**Pull request merged**
