### PR TITLE
Add photo/trace individual pages

### PR DESCRIPTION
**Pull request by vgeorge**
Changelog:

- Added styles to traces table
- Added individual photo page
- Added indificual trace page
- Added links to individual pages at photos/trace pages

### CODE REVIEW

**Comment by LanesGood** [comment]
@vgeorge FYI I had to clear my yarn cache to get this branch running, learned from the issue here:
https://github.com/yarnpkg/yarn/issues/7584

I'm now getting the login error again, `502 Bad Gateway | nginx/1.16.1` - do I need to kickstart the server somehow?

**Comment by vgeorge** [comment]
@LanesGood that was probably an error I introduced to the staging API by having to deploy it manually, it should be fixed now. I hope we can find soon a way to deploy from Circle to avoid this.

**Comment by vgeorge** [comment]
@LanesGood I did updates in the photo view page, I believe it's more complete now. I not planning to add more changes to this PR, you can work on style updates. Please let me know when you are finishs so I can review.

**Comment by LanesGood** [comment]
@vgeorge I've finished styling the individual pages

A few notes:
- I turned the `Infobox` component contents into a form element with the thought that this might help make switching the editable descriptions on and off easier, and allow for greater control over styling when edit mode is "on"
- I added more styles to the list pages while I was at it.
- I also added the Dropdown range slider on the list page to see what it looks like - happy to remove if it shouldn't be in this branch
- I'll work on responsiveness in a separate branch.

**Comment by vgeorge** [comment]
Thanks @LanesGood, updates look really good. Merging this as now we have more surface to work in separate PRs.

**Pull request merged**
