### PR TITLE
Traces page

### PR DESCRIPTION
**Pull request by vgeorge**
The goal of this PR is to implement components for traces page according to the wireframes (#12).

At the moment, this PR includes:

- State persistance, user will keep login after page reload
- Loading traces from the API
- Display of total traces count

To do:

- [x] Filter components
- [x] Pagination components
- [x] Table

### CODE REVIEW

**Comment by vgeorge** [comment]
@LanesGood I believe you can work on styling what you can for this page while I implement the Photos page. In order to populate the development database, please use code from https://github.com/developmentseed/observe-api/pull/25 for the moment.

**Comment by LanesGood** [comment]
@vgeorge I'm running the API locally from the branch in developmentseed/observe-api#25 but the dev db is not populating.

**Comment by LanesGood** [comment]
@vgeorge I've started setting up the layout for the pagination, and for the dropdown + length slider featured in [this screen](https://invis.io/JYU854UR3TF#/390342201_Traces_Table_LengthFilter-Hifi). Would you be able to help me hook up the dropdown and length filter so that I can start styling? This is mainly using components developed by @danielfdsilva that I'm not able to implement yet solo.

/cc @sethvincent if you want to take a look

**Comment by vgeorge** [comment]
@LanesGood as discussed, I'm merging this at the commit with basic page structure. I've moved last commits to `enhance/trace-page-styles` branch. Let's  work on specific components in separate PRs to be able to review better.

**Pull request merged**
